language: python
sudo: false
cache: pip
matrix:
  include:
    - python: '3.4'
      env:
        - TOXENV=py34
    - python: '3.5'
      env:
        - TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip3 --version
  - pip3 install tox flake8 bandit sphinx
  - pip3 freeze
script:
  - make all
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
